version: '3.8'

services:
  web:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    command:   gunicorn doguide.wsgi:application --bind 0.0.0.0:7000
    image: manulangat/auto-deploy-do-github-actions:latest
    ports:
      - "7000:7000"
    env_file:
       - ./.env
    networks:
      - ci-cd-django-app
  
  
networks:
  ci-cd-django-app:
    