name: Continuous Integration and Dev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Django tests
        run: |
          docker-compose run web python manage.py test

      - name: Build the stack
        run: docker-compose up -d --build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: docker-compose push

      - name: Stop containers
        run: docker-compose down --volumes
